### ISSUE TITLE
Headline says 2.0 

### ISSUE THREAD

**Issue by GunnarLieb** [kevindb/cf-mailchimp#4]
ColdFusion wrapper for the MailChimp 2.0 API
while it's 3.0

What's about putting it on Forgebox, I can do a PR for  box.sjon file if you like?

**Comment by kevindb** [comment]
Thanks, the headline has been updated.

Yes, I'd love a PR for Forgebox support. I've created an account on Forgebox, so I can publish after merging the PR.

**Comment by GunnarLieb** [comment]
Would you mind making it a Coldbox module as well? This would simply mean renaming src folder to models. Would work with src as well, but the convention is models. I would add as well a moduleconfig.cfc
