### ISSUE TITLE
Running on Lucee

### ISSUE THREAD

**Issue by GunnarLieb** [kevindb/cf-mailchimp#5]
I could not get the http calls running on Lucee, instead of supplying username and password I had to do 
```
		httpService = new http(url=local.url, method="get");
		httpService.addParam(type="header",name="Authorization", value="apikey #getApiKey()#");
```
Can you check if this works as well on ACF

**Comment by kevindb** [comment]
This looks very similar to #2. **Would you please provide a link to MailChimp's documentation showing use of the Authorization header?**

All that I've been able to find is this, using basic HTTP authentication using username and password.
https://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/#authentication

**Comment by kevindb** [comment]
Closing due to lack of info. This issue can be reopened if need be.
